modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/thelegitdolt/bowling-bulb/issues"
license = "https://github.com/thelegitdolt/bowling-bulb/issues"

[[mods]]
modId = "bowling_bulb"
version = "${file.jarVersion}"
authors = "Dolt"
credits = "Dolt H. Haven"
displayName = "Bowling Bulb"
description = '''
        Bowling Bulb eats bowls. Download this mod to feed him more bowls
'''

[[dependencies.bowling_bulb]]
    modId = "emi"
    mandatory = false
    versionRange = "[1.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.bowling_bulb]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.3.0,)"
    ordering = "AFTER"
    side = "BOTH"
